name: CI
on:
 push:
  branches:
   - main
jobs:

 build-mac:
  runs-on: macos-latest
  permissions:
   contents: write
  steps:
   - uses: actions/checkout@v2
   - name: prepare dependencies
     run: |
      brew install --cask xquartz
      brew install pango

   - name: make
     run: |
      make TARGET=MACOS
      mv zundagame zundagame-mac

   - uses: xresloader/upload-to-github-release@v1
     with:
      file: zundagame-mac
      draft: false

 build-wasm:
  runs-on: ubuntu-latest
  permissions:
   contents: read
   pages: write
   id-token: write

  steps:
   - uses: actions/checkout@v2
   - name: prepare emscripten
     run: sudo apt-get -y install emscripten
   
   - name: make
     run: make TARGET=WASM
   - name: prepare page content
     run: |
      mkdir deploy
      mv zundagame.wasm deploy/
      mv img deploy/
      mv adwaitalegacy deploy/
      mv wasm/index* deploy/

   - uses: actions/configure-pages@v5
   - uses: actions/upload-pages-artifact@v3
     with:
      path: deploy
   - uses: actions/deploy-pages@v4
