name: CI

on:
 push:
  branches:
   - main

jobs:
 build-linux:
  runs-on: ubuntu-latest

  steps:

   - name: install dependics
     run: sudo apt-get install -y libcairo2-dev libx11-dev libpango1.0-dev

   - uses: actions/checkout@v2

   - name: build program
     run: make

   - name: make program package
     run: tar cvf zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz img adwaitalegacy zundagame readme.md

   - uses: xresloader/upload-to-github-release@v1
     name: upload artifacts
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz
      draft: false

 build-windows:
  runs-on: windows-latest

  steps:

   - uses: actions/checkout@v2
   
   - uses: robinraju/release-downloader@v1
     name: download gvsbuild
     with:
      repository: 'wingtk/gvsbuild'
      latest: true
      filename: 'GTK3*.zip'
      extract: true
      out-file-path: 'gtk3'

   - uses: msys2/setup-msys2@v2

   - name: msys2 build steps
     run : |
      gtk3/bin/pkg-config --libs --cflags cairo
      

