name: CI

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: install dependics
     run: apt-get install libcairo2-dev libx11-dev libpango1.0-dev
   - name: build program
     run: make
