name: CI

on:
 push:
  branches:
   - main

jobs:
 build-linux:
  runs-on: ubuntu-latest

  steps:

   - name: install dependics
     run: sudo apt-get install -y libcairo2-dev libx11-dev libpango1.0-dev

   - uses: actions/checkout@v2

   - name: build program
     run: make

   - name: make program package
     run: tar cvf zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz img adwaitalegacy zundagame readme.md

   - uses: xresloader/upload-to-github-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz
      draft: false

 build-windows:
  runs-on: windows-latest

  steps:

   - uses: actions/checkout@v2

   - uses: msys2/setup-msys2@v2

   - name: msys2 build steps
     run : |
      curl -o gvsbuild.zip https://github.com/wingtk/gvsbuild/releases/download/2024.12.0/GTK3_Gvsbuild_2024.12.0_x64.zip
      7z x gvsbuild.zip
      

