name: CI
on:
 push:
  branches:
   - main

jobs:

 build-linux:
  runs-on: ubuntu-latest
  permissions:
   contents: read 
  steps:
   - uses: actions/checkout@v2
   - name: prepare dependics
     run: sudo apt-get install -y libcairo2-dev libpango1.0-dev
   - name: build
     run: make
   - name: upload release
     uses: xresloader/upload-to-github-release@v1
     with:
      file: zundagame
      draft: false
