name: CI

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Check out repository code
     uses: actions/checkout@v3
   - name: build program
     run: make
