name: CI

on:
 push:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:

   - name: install dependics
     run: sudo apt-get install -y libcairo2-dev libx11-dev libpango1.0-dev

   - name: code checkout
     uses: actions/checkout@v2

   - name: build program
     run: make

   - name: make program package
     run: tar cvf zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz img adwaitalegacy zundagame readme.md

   - name: Upload artifact
     uses: xresloader/upload-to-github-release@v1
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz
      draft: false
      default_release_body: Automated build in `$(date)` by github actions.
