name: CI

on:
 push:
  branches:
   - main

jobs:
 build-linux:
  runs-on: ubuntu-latest

  steps:

   - name: install dependics
     run: sudo apt-get install -y libcairo2-dev libx11-dev libpango1.0-dev

   - uses: actions/checkout@v2

   - name: build program
     run: make

   - name: make program package
     run: tar cvf zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz img adwaitalegacy zundagame readme.md

   - uses: xresloader/upload-to-github-release@v1
     name: upload artifacts
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-linux-${{ github.RUN_NUMBER }}.tar.gz
      draft: false

 build-macos:
  runs-on: macos-latest

  steps:
  
   - uses: actions/checkout@v2

   - name: install build dependencies
     run: |
      brew install --cask xquartz
      brew install pango

   - name: build
     run: make -f makefile-macos

   - name: package program
     run: tar cvf zundagame-bin-macos-${{ github.RUN_NUMBER }}.tar.gz img adwaitalegacy zundagame readme.md

   - uses: xresloader/upload-to-github-release@v1
     name: upload artifacts
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-macos-${{ github.RUN_NUMBER }}.tar.gz
      draft: false

 build-windows:
  runs-on: windows-latest

  steps:

   - uses: actions/checkout@v2
   
   - uses: robinraju/release-downloader@v1
     name: download gvsbuild
     with:
      repository: 'wingtk/gvsbuild'
      latest: true
      filename: 'GTK3*.zip'
      extract: true
      out-file-path: 'gtk3'

   - uses: msys2/setup-msys2@v2
     id: msys2
     with:
      msystem: MSYS

   - name: msys2 build steps
     run : |
      make -f makefile-win
      cp ${{ steps.msys2.outputs.msys2-location }}/usr/bin/msys-2.0.dll .
      7z a zundagame-bin-windows-msys2-gvsbuild-${{ github.RUN_NUMBER }}.zip adwaitalegacy img zundagame.exe readme.md msys-2.0.dll

   - uses: xresloader/upload-to-github-release@v1
     name: upload artifacts
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
      file: zundagame-bin-windows-msys2-gvsbuild-${{ github.RUN_NUMBER }}.zip
      draft: false

 build-wasm:
  runs-on: ubuntu-lastest

  steps:

   - uses: action/checkout@v2
   
   - name: build program
     run: make -f makefile-emscripten

   - name: upload to separate branch
     run: |
       git branch deploy
       git add zundagame.wasm
       git commit -m "wasm auto build"
